In [1]:
import numpy as np

### Одномерные массивы

In [2]:
a = [1, 2, 5]
b = [5, 6, 7]

In [3]:
a + b

[1, 2, 5, 5, 6, 7]

In [4]:
a = np.array(a)
b = np.array(b)

In [5]:
a

array([1, 2, 5])

In [6]:
a.dtype

dtype('int32')

In [7]:
a + b

array([ 6,  8, 12])

In [8]:
a * b

array([ 5, 12, 35])

In [9]:
np.dot(a, b)

52

In [19]:
a.shape

(3,)

In [16]:
ac = a.reshape((3,1))

In [17]:
ac

array([[1],
       [2],
       [5]])

In [18]:
ac.shape

(3, 1)

In [20]:
a[1]

2

In [21]:
a[1] = 2

In [22]:
a

array([1, 2, 5])

In [23]:
a > 1.5

array([False,  True,  True])

In [24]:
a[a > 1.5]

array([2, 5])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(20) * 4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4.])

### Двумерные массивы

In [27]:
mat = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])

In [28]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
mat.shape

(3, 3)

In [30]:
mat[0, 2]

15

In [33]:
mat[:, 1:4]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [34]:
a

array([1, 2, 5])

In [35]:
mat * a

array([[  5,  20,  75],
       [ 20,  50, 150],
       [ 35,  80, 225]])

In [43]:
a_col = a.reshape((3,1))

In [44]:
a_col

array([[1],
       [2],
       [5]])

In [45]:
np.dot(mat, a_col)

array([[100],
       [220],
       [340]])

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])