In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns; sns.set()

ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

In [4]:
from sklearn.datasets import fetch_lfw_people
faces = fetch_lfw_people(min_faces_per_person=60)
print(faces.target_names)
print(faces.images.shape)

/home/ni2633244/anaconda3/lib/python3.5/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array


['Ariel Sharon' 'Colin Powell' 'Donald Rumsfeld' 'George W Bush'
 'Gerhard Schroeder' 'Hugo Chavez' 'Junichiro Koizumi' 'Tony Blair']
(1348, 62, 47)


In [6]:
flist = []
for i in faces.images:
    flist.append(np.ravel(i))
farr = np.array(flist)
print(farr)

[[ 138.          135.66667175  127.66666412 ...,    1.66666663
     1.66666663    0.33333334]
 [  71.33333588   56.           67.66666412 ...,  247.66667175  243.
   238.33332825]
 [  84.33333588   97.33333588   72.33333588 ...,  114.          194.33332825
   241.        ]
 ..., 
 [  29.33333397   29.           29.33333397 ...,  145.          147.
   141.66667175]
 [  49.33333206   55.66666794   76.66666412 ...,  186.33332825
   176.33332825  161.        ]
 [  31.           26.33333397   28.         ...,   34.           42.
    69.66666412]]


In [25]:
from sklearn.model_selection import train_test_split
X=farr
y=faces.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [29]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [30]:
pred = knn.predict(X_test)

In [31]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, pred))

[[  8   7   1   3   0   0   0   2]
 [  1  54   0  19   0   0   0   1]
 [  3   8  14  17   0   0   0   0]
 [  3  14   4 127   5   1   0   5]
 [  0   3   3  16   3   0   0   4]
 [  0   2   0  11   2   6   0   0]
 [  0   1   0   3   0   0   6   0]
 [  0   4   4  25   2   1   1  11]]
